version: '3.8'

services:

  postgres_db:
    image: postgres:16-alpine
    container_name: org_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_department
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_department"]
      interval: 5s
      timeout: 5s
      retries: 5


  web_app:
    build: .
    container_name: org_api
    ports:
      - "6969:6969"

    depends_on:
      postgres_db:
        condition: service_healthy
    restart: always


volumes:
  pgdata: